export const lazyMessages = [
    "fix",
    "fixes",
    "bug fix",
    "urgent fix",
    "quick fix",
    "minor fix",
    "small fix",
    "hotfix",
    "update",
    "updates",
    "minor update",
    "small update",
    "test",
    "testing",
    "wip",
    "work in progress",
    "temp",
    "temporary",
    "tmp",
    "chore",
    "misc",
    "cleanup",
    "refactor",
    "changes",
    "stuff",
    "things",
    "adjustments",
    "improvements",
    "tweak",
    "tweaks",
    "more changes",
    "final",
    "final fix",
    "last fix",
    "again",
    "retry",
    "try again",
    "another fix",
    "commit",
    "save",
    "progress",
    "oops",
    "forgot",
    "missing",
    "typo",
    "lint",
    "format",
    "formatting",
    "style",
    "ui fix",
    "quick changes",
    "minor changes",
    "fixes",
];